package com.example.crypto

/**
 * Curated EFF large list subset of memorable, distinct, English words for Passphrase generation.
 */
object WordList {
    val WORDS: List<String> = listOf(
        "abacus", "abbey", "ability", "ablaze", "abode", "abrupt", "absent", "absorb", "abstract", "abundant",
        "academy", "accent", "acorn", "acoustic", "acquire", "across", "action", "active", "actor", "adapt",
        "address", "admire", "adopt", "advance", "aerial", "affect", "afford", "agency", "agenda", "agree",
        "airplane", "airport", "alarm", "album", "alchemy", "alert", "algebra", "alien", "align", "allege",
        "alley", "alligator", "almond", "alpine", "alright", "altitude", "aluminum", "always", "amber", "ambient",
        "amend", "amethyst", "amplify", "anchor", "ancient", "angel", "angle", "animal", "animate", "ankle",
        "antenna", "antique", "anvil", "apology", "apple", "apron", "aquarium", "arcade", "arch", "arctic",
        "arena", "argon", "armor", "aroma", "arrow", "artery", "artist", "ascend", "ash", "aspect",
        "asphalt", "assemble", "asteroid", "atlas", "atom", "atomic", "attach", "attack", "attain", "attic",
        "audio", "august", "aura", "author", "autumn", "avatar", "avenue", "avocado", "awake", "axis",
        "bacon", "badge", "bagel", "baker", "balance", "balcony", "ballad", "balloon", "bamboo", "banana",
        "banner", "barber", "bargain", "barley", "barn", "barrel", "barrier", "basalt", "baseline", "basket",
        "beacon", "beaker", "beam", "bear", "beauty", "beetle", "behave", "beloved", "bench", "benefit",
        "berry", "bicycle", "binary", "biology", "birch", "biscuit", "bison", "bitter", "blade", "blanket",
        "blaze", "blend", "blessing", "blizzard", "block", "blossom", "blueberry", "board", "boat", "boulder",
        "bounce", "boundary", "brave", "breeze", "brick", "bridge", "brilliant", "bronze", "bubble", "bucket",
        "buffalo", "builder", "bulletin", "bundle", "buoyant", "burrow", "butter", "cabin", "cactus", "cadet",
        "calendar", "calm", "camera", "camp", "canopy", "canyon", "captain", "caravan", "carbon", "cardinal",
        "cargo", "carpet", "cascade", "castle", "catalyst", "catcher", "cater", "cedar", "celestial", "cement",
        "century", "ceramic", "cereal", "chain", "chalk", "champion", "channel", "chapter", "charcoal", "chariot",
        "chart", "chasm", "cheese", "chemical", "cherry", "chest", "chimney", "chipmunk", "chord", "cider",
        "cinnamon", "cipher", "circuit", "circus", "citadel", "citizen", "citrus", "civic", "clarity", "clay",
        "clever", "cliff", "climate", "climb", "cloak", "clock", "clover", "cluster", "cobalt", "coconut",
        "coffee", "cohesion", "collar", "colony", "column", "comet", "compass", "complex", "composer", "compost",
        "concept", "concrete", "condor", "conduit", "connect", "conquer", "console", "constant", "copper", "coral",
        "cordial", "cork", "corner", "cosmos", "cottage", "cotton", "council", "courage", "cove", "cradle",
        "craft", "crane", "crater", "creek", "crescent", "crest", "cricket", "crimson", "crisp", "crown",
        "crystal", "cube", "culprit", "culture", "curiosity", "current", "curtain", "cushion", "custom", "cyclone",
        "cylinder", "dagger", "dairy", "daisy", "damage", "dance", "danger", "daring", "daylight", "dazzle",
        "debris", "decade", "decimal", "decode", "decor", "decoy", "defender", "defiance", "degree", "delegate",
        "delight", "deliver", "delta", "density", "dentist", "deposit", "depth", "deputy", "desert", "design",
        "desire", "desktop", "destroy", "detail", "detect", "develop", "device", "dew", "diagonal", "diagram",
        "dial", "diamond", "diary", "dignity", "diligent", "dimension", "dinosaur", "diploma", "director", "discovery",
        "dish", "display", "distance", "diver", "divide", "dock", "doctor", "dolphin", "domain", "dome",
        "donor", "doorway", "dolphin", "dragon", "drain", "drapery", "dream", "drift", "drill", "driver",
        "drum", "dryer", "duck", "dune", "duplicate", "dusk", "dynamic", "eagle", "earring", "earth",
        "easel", "echo", "eclipse", "ecology", "economy", "edition", "educate", "effort", "elastic", "elder",
        "electric", "element", "elephant", "elevator", "elite", "elm", "embark", "embassy", "ember", "emerald",
        "emission", "emotion", "empathy", "empire", "empower", "enchant", "encore", "endorse", "energy", "engine",
        "enigma", "enjoy", "enrich", "ensemble", "entity", "entrance", "envelope", "epic", "episode", "epoch",
        "equality", "equation", "equator", "equity", "era", "escape", "escort", "essay", "essence", "estate",
        "eternal", "ethics", "ethos", "evaporate", "evergreen", "evident", "evolution", "exact", "exalt", "example",
        "excel", "exchange", "excite", "excursion", "execute", "exempt", "exercise", "exhibit", "exile", "exit",
        "expand", "expedition", "expert", "explorer", "exponent", "express", "extend", "exterior", "extra", "fabric",
        "facade", "factor", "factory", "faculty", "falcon", "fame", "fantasy", "farmer", "fashion", "fasten",
        "father", "fatigue", "feather", "feature", "federal", "feedback", "fellow", "fence", "fern", "ferry",
        "festival", "fiber", "fiction", "fidelity", "field", "fierce", "figure", "filter", "final", "finance",
        "finch", "finger", "fir", "firefly", "firmware", "fish", "fitness", "flame", "flannel", "flare",
        "flash", "flavor", "fleet", "flex", "flight", "flint", "floating", "flood", "floral", "flourish",
        "flow", "fluent", "flute", "flux", "flyer", "foam", "focus", "fog", "folder", "foliage",
        "folk", "font", "footstep", "forage", "force", "forecast", "forest", "forge", "format", "formula",
        "fortress", "fortune", "forum", "fossil", "foster", "foundry", "fountain", "fox", "fraction", "fragment",
        "fragrant", "frame", "freedom", "frequency", "fresh", "friction", "frigate", "frost", "frontier", "fruit",
        "fuel", "fulfill", "fulcrum", "funnel", "furnace", "fusion", "future", "gadget", "galaxy", "galley",
        "gallon", "galvanic", "garden", "garland", "garment", "garnet", "gasoline", "gateway", "gauge", "gazelle",
        "gear", "gemini", "general", "generate", "generator", "generic", "generous", "genesis", "genetic", "genius",
        "gentle", "genuine", "geology", "geometry", "geyser", "giant", "ginger", "giraffe", "glacier", "glade",
        "glamour", "glance", "glass", "glider", "glimmer", "glimpse", "globe", "glorious", "glossary", "glow",
        "glucose", "glyph", "goal", "goblet", "goddess", "golden", "goldfish", "gondola", "goodwill", "gopher",
        "gorge", "gorilla", "governor", "grace", "gradient", "gradual", "grain", "grammar", "granite", "grape",
        "graphic", "graphite", "grass", "gravity", "grazing", "greatness", "green", "greeting", "grid", "griffin",
        "groove", "ground", "grove", "growth", "guard", "guest", "guidance", "guitar", "gulf", "gull",
        "habitat", "hail", "hammer", "hammock", "hamster", "handbook", "handle", "harbor", "harmony", "harvest",
        "haven", "hawk", "hazard", "hazel", "header", "heading", "headland", "headlight", "healing", "health",
        "heartland", "hearth", "heater", "heaven", "heavy", "hedgehog", "height", "helium", "helmet", "helper",
        "herald", "heritage", "heroic", "heron", "hexagon", "hibiscus", "hickory", "hidden", "highway", "hiking",
        "hillside", "history", "hive", "hobby", "hockey", "holding", "holiday", "hollow", "holly", "hologram",
        "homeland", "honest", "honey", "hood", "horizon", "horn", "hornet", "horse", "hospital", "host",
        "hotspot", "hour", "house", "hover", "hub", "humble", "humidity", "hummingbird", "hunter", "hurricane",
        "hybrid", "hydrant", "hydrogen", "hydrology", "hygiene", "hyper", "hyphen", "iceberg", "icon", "ideal",
        "identity", "idle", "igloo", "ignition", "illuminate", "illusion", "illustrate", "image", "imagine", "impact",
        "impala", "imperial", "implode", "import", "impose", "impress", "impulse", "inch", "incident", "include",
        "income", "increase", "incubate", "index", "indicate", "indices", "indigo", "individual", "indoor", "induce",
        "industry", "infant", "inferno", "infinite", "infinity", "inflate", "influence", "inform", "infrared", "ingenious",
        "ingredient", "inhabit", "inhale", "initial", "inject", "ink", "inlet", "inline", "innocence", "innovate",
        "input", "inquire", "insect", "insight", "inspire", "install", "instant", "instinct", "instruct", "instrument",
        "insulin", "intact", "integral", "integrity", "intellect", "intense", "intent", "interact", "intercept", "interest",
        "interface", "interior", "internal", "internet", "interval", "intimate", "intrepid", "intrigue", "intrinsic", "intro",
        "intrude", "intuition", "invade", "invent", "inventory", "invest", "invisible", "invite", "invoke", "involve",
        "iodine", "ion", "iris", "iron", "ironclad", "ironic", "ironwood", "irradiate", "island", "isolate",
        "isotope", "issue", "italic", "item", "iterate", "ivory", "ivy", "jacket", "jaguar", "jamboree",
        "january", "jasmine", "jasper", "java", "javelin", "jazz", "jealousy", "jellyfish", "jeopardy", "jersey",
        "jester", "jetliner", "jetstream", "jigsaw", "jockey", "jogger", "join", "journal", "journey", "jovial",
        "joyful", "jubilant", "judge", "judo", "juggler", "juice", "jukebox", "july", "jumbo", "jump",
        "junction", "june", "jungle", "junior", "juniper", "jupiter", "juror", "justice", "justify", "juvenile",
        "kangaroo", "karate", "kayak", "keep", "keeper", "kelp", "kennel", "kernel", "kestral", "ketchup",
        "kettle", "key", "keyboard", "keyhole", "keystone", "keyword", "kickoff", "kidney", "kilometer", "kimono",
        "kindle", "kindred", "kinetic", "kingdom", "kingfisher", "kiosk", "kite", "kitten", "kiwi", "knapsack",
        "knee", "knife", "knight", "knitting", "knob", "knot", "knowledge", "koala", "krypton", "kudos"
    )
}
